### ISSUE TITLE
Firebase Storage版アップローダーを「有効化しない」場合にそれを明示的に反映する

### ISSUE THREAD

**Issue by cmplstofB** [flocon-trpg/servers#638]
こんにちは。

前提環境
Floconツール: 2023-03-24現在
Webサーバー: 0.8.10
APIサーバー: 0.7.15

2023-03-24現在，Floconツールの[Webサーバーの設定を作成する](https://tools.flocon.app/web-server)ページにおいて，
「Firebase Storage版アップローダーを有効化する」という項目は既定で「有効化する」にチェックが入った状態となっており，
設定ファイルの内容には
`NEXT_PUBLIC_FIREBASE_STORAGE_ENABLED=true`
という行が含まれています。

ここで，「有効化する」のチェックを外すと，
`NEXT_PUBLIC_FIREBASE_STORAGE_ENABLED=true`
の行が**まるごと**消えます。
しかしこの（`...STORAGE_ENABLED=...`行が無い）状態の設定ファイル (env.txtや.env.local) を用いると，
Webサーバー上のアップローダーの選択肢としてFirebase Storageが表示されてしまいます。
（Webサーバー: 0.8.10，APIサーバー: 0.7.15）
これはUIとして意図した動作ではないと思います。

設定ファイル内で
`NEXT_PUBLIC_FIREBASE_STORAGE_ENABLED=false`
と明示すると，WebサーバーのアップローダーからFirebase Storageの選択肢は見えなくなります。

以上から，Floconツールで
「Firebase Storage版アップローダーを有効化する」項目のチェックを外した場合に，
`NEXT_PUBLIC_FIREBASE_STORAGE_ENABLED=false`
というように，Firebase Storageを無効化することを明示的に反映したほうが良いと思います。

**Comment by kizahasi** [comment]
https://github.com/flocon-trpg/tools の中身をこのリポジトリに統合したため、この issue もこちらに transfer しました。

ご指摘ありがとうございます。返事が大変遅れてしまい申し訳ありません…🙇

おっしゃるとおり、問題があることを確認しました。 2394bd8 (と 05ce2b5) で統合の作業を行った際に一緒に修正されたと思います。https://3fc29340.flocon.pages.dev/tools/web-server/ からプレビューできます。まだ Web サイトのほうには反映されていませんが、近いうちに反映させる予定です。

**Comment by kizahasi** [comment]
サイト https://flocon.app/tools/web-server/ に反映させたのでこの issue は close します。
